zephlack.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack.c -o zephlack.lo 
kernel/main.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/exit.lo: /home/nathan/PhpstormProjects/zephlack/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/kernel/exit.c -o kernel/exit.lo 
zephlack/message/message.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/message.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/message.zep.c -o zephlack/message/message.lo 
zephlack/message/messageattachment.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messageattachment.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messageattachment.zep.c -o zephlack/message/messageattachment.lo 
zephlack/message/messageexception.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messageexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messageexception.zep.c -o zephlack/message/messageexception.lo 
zephlack/message/messagefield.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messagefield.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messagefield.zep.c -o zephlack/message/messagefield.lo 
zephlack/message/messageinterface.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messageinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/message/messageinterface.zep.c -o zephlack/message/messageinterface.lo 
zephlack/client.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/client.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/client.zep.c -o zephlack/client.lo 
zephlack/clientexception.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/clientexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/clientexception.zep.c -o zephlack/clientexception.lo 
zephlack/collection.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/collection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/collection.zep.c -o zephlack/collection.lo 
zephlack/http/header.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/header.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/header.zep.c -o zephlack/http/header.lo 
zephlack/http/httpexception.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/httpexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/httpexception.zep.c -o zephlack/http/httpexception.lo 
zephlack/http/request.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/request.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/request.zep.c -o zephlack/http/request.lo 
zephlack/http/response.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/response.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/response.zep.c -o zephlack/http/response.lo 
zephlack/http/uri.lo: /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/uri.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/nathan/PhpstormProjects/zephlack/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/nathan/PhpstormProjects/zephlack/ext/zephlack/http/uri.zep.c -o zephlack/http/uri.lo 
$(phplibdir)/zephlack.la: ./zephlack.la
	$(LIBTOOL) --mode=install cp ./zephlack.la $(phplibdir)

./zephlack.la: $(shared_objects_zephlack) $(ZEPHLACK_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_zephlack) $(ZEPHLACK_SHARED_LIBADD)

